---
# tasks file for linux
- name: Register OS version as new variable
  shell: cat /etc/*-release | grep PRETTY_NAME | cut -d = -f 2 | tr -d '\"'
  register: os_used


- block:
  - name: Print error message
    debug: msg="{{ error_msg }}"
  when: os_used.stdout != os_required
# An alternative way to write the condition is below, but not all distributions include the lsb package by default. This block will crash with an error, because ansible_lsb does not contain "description" field.
#  when: ansible_lsb.description != os_required


- block:
  - name: Create user
    user:
      name: "{{ username }}"
      password: "{{ '{{ userpassword }}' | password_hash('sha512') }}"

  - name: Allow connection for user via ssh
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^AllowUsers '
      line: AllowUsers cloudru
    notify: Restart SSH

  - name: Deny connection for root via ssh
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin '
      insertafter: '^#PermitRootLogin '
      line: PermitRootLogin no
    notify: Restart SSH

  - name: Create directory for public key
    file: path={{ dest_folder }} state=directory

  - name: Copy public key
    copy:
      dest: /home/{{ username }}/.ssh/authorized_keys
      content: "'{{ ssh_public_key }}'"

  - name: Close password authentication in ssh
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication '
      insertbefore: '^#PermitEmptyPasswords '
      line: PasswordAuthentication yes
    notify: Restart SSH

  when: os_used.stdout == os_required
# An alternative way to write the condition is below, but not all distributions include the lsb package by default. This block will work correct, but another will not.
#  when: ansible_lsb.description == os_required

